build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:buster"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:buster"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:buster"
  armv7: "ghcr.io/home-assistant/armv7-base-debin:buster"
  i386: "ghcr.io/home-assistant/i386-base-debian:buster"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Meross Local"
  org.opencontainers.image.description: "Implements Meross cloud services locally."
  org.opencontainers.image.licenses: "Apache License 2.0"
squash: false
